In [1]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\amitm\appdata\local\programs\python\python311\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\amitm\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\amitm\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\amitm\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\amitm\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import joblib

In [4]:
df = pd.read_csv("F:\\01. The Data Psychology\\4. New_Machine_Learning\\4. Naive Bay's\\04. Placement Data.xls")

In [5]:
df.head(5)

   Unnamed: 0 grade  cgpa   iq  communication  technical_knowledge  placement
0           0     B  7.34  124              1                    7          0
1           1     D  8.88  112              1                    5          0
2           2     C  7.95   85              8                    8          0
3           3     B  6.42  103              8                    8          1
4           4     A  6.10   98              6                    9          1

In [6]:
df = df.iloc[:, 1:]

In [7]:
df.head(2)

  grade  cgpa   iq  communication  technical_knowledge  placement
0     B  7.34  124              1                    7          0
1     D  8.88  112              1                    5          0

In [8]:
df.shape

(500, 6)

In [9]:
df.isnull().sum()

grade                  0
cgpa                   0
iq                     0
communication          0
technical_knowledge    0
placement              0
dtype: int64

In [10]:
df.dtypes

grade                   object
cgpa                   float64
iq                       int64
communication            int64
technical_knowledge      int64
placement                int64
dtype: object

In [11]:
df.duplicated().sum()

0

In [13]:
le = LabelEncoder()

In [15]:
df["grade"]= le.fit_transform(df["grade"])

In [16]:
df["grade"]

0      1
1      3
2      2
3      1
4      0
      ..
495    1
496    1
497    0
498    3
499    3
Name: grade, Length: 500, dtype: int32

In [17]:
df.dtypes

grade                    int32
cgpa                   float64
iq                       int64
communication            int64
technical_knowledge      int64
placement                int64
dtype: object

In [19]:
X = df.drop("placement", axis=1)

In [20]:
X.head()

   grade  cgpa   iq  communication  technical_knowledge
0      1  7.34  124              1                    7
1      3  8.88  112              1                    5
2      2  7.95   85              8                    8
3      1  6.42  103              8                    8
4      0  6.10   98              6                    9

In [21]:
y = df.placement

In [22]:
y

0      0
1      0
2      0
3      1
4      1
      ..
495    1
496    1
497    1
498    0
499    0
Name: placement, Length: 500, dtype: int64

In [23]:
x_train, x_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=45)

In [24]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((400, 5), (100, 5), (400,), (100,))

In [25]:
x_train

     grade  cgpa   iq  communication  technical_knowledge
484      1  6.82   99              2                    8
166      1  8.17  139             10                    6
455      1  7.67  136              3                    8
63       1  5.94  127              1                   10
180      1  4.96  106              6                    4
..     ...   ...  ...            ...                  ...
32       0  8.18  121              8                    8
380      0  6.97  110              8                    3
131      0  6.02  118              4                    4
414      1  7.94   91              8                    1
459      0  7.49  116              7                   10

[400 rows x 5 columns]

In [26]:
x_test

     grade  cgpa   iq  communication  technical_knowledge
204      1  7.07  125              2                    9
481      1  7.33  120              2                    2
296      2  6.48   90              7                   10
38       1  7.65  118              4                    1
298      1  5.78   82              8                    2
..     ...   ...  ...            ...                  ...
79       0  6.78   83              9                    9
476      0  8.55   89              1                    5
69       3  6.21  120              3                    5
73       2  5.80  139             10                    5
138      1  6.24  111              5                    9

[100 rows x 5 columns]

In [29]:
scaler = StandardScaler()

In [30]:
x_train_scale = scaler.fit_transform(x_train)

In [36]:
x_test_scale = scaler.transform(x_test)

In [37]:
nb = GaussianNB()

In [38]:
nb.fit(x_train_scale,y_train)

GaussianNB()

In [40]:
nb.score(x_test_scale, y_test)

0.87